name: MacRDP

on:
  workflow_dispatch:

jobs:
  build:
    name: MacOS via Namespace
    runs-on: namespace-profile-batissh

    steps:
      - name: Set up Remote Desktop Access
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          curl -s -o start.sh -L "https://raw.githubusercontent.com/JohnnyNetsec/github-vm/main/mac/start.sh"
          chmod +x start.sh
          bash start.sh "$NGROK_AUTH_TOKEN"

      - name: Start Live Debug Session
        uses: mxschmitt/action-tmate@v2
